version: '3.1'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hexagonal
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
